[package]
name = "gol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { version = "0.17.3", features = ["rayon"] }
itertools = "0.10.5"
lazy_static = "1.4"
rand = "0.8"
rayon = "1.7.0"
ril = { version = "0.9.0", features = ["png"] }
